version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: ./containers/rails/Dockerfile
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/myapp
      - tmp-data:/myapp/tmp
      - public-data:/myapp/public
    ports:
      - 3000:3000
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    volumes:
      - tmp-data:/myapp/tmp
      - public-data:/myapp/public
    ports:
      - 80:80
    depends_on:
      - rails
  db:
    image: mysql:5.7
    env_file: .env
    volumes:
      - DB-data:/var/lib/mysql

volumes:
  DB-data:
  tmp-data:
  public-data:
