version: '3'

services:

  rails:
    build:
      context: .
      dockerfile: ./containers/rails/Dockerfile
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./backend:/myapp
      - tmp-data:/myapp/tmp
      - public-data:/myapp/public
    hostname: rails
    depends_on:
      - db

  react:
    build:
      context: .
      dockerfile: ./containers/react/Dockerfile
    command: sh -c "yarn start"
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 8000:3000
    depends_on:
      - rails

  nginx-front:
    build:
      context: .
      dockerfile: ./containers/nginx-front/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80
    depends_on:
      - react

  nginx-api:
    build:
      context: .
      dockerfile: ./containers/nginx-api/Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - tmp-data:/myapp/tmp
      - public-data:/myapp/public
    ports:
      - 3000:3000
    depends_on:
      - react

  db:
    image: mysql:5.7
    env_file: .env
    volumes:
      - DB-data:/var/lib/mysql

volumes:
  DB-data:
  tmp-data:
  public-data:
