name: Run Rspec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set .env File
        shell: bash
        run: |
          touch .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env

      - name: Docker Compose Up
        shell: bash
        run: |
          docker compose build
          docker compose up -d

      - name: Create DB
        shell: bash
        run: |
          docker compose exec -T rails rails db:create

      - name: Run Rspec
        shell: bash
        env:
          RAILS_ENV: test
        run: |
          docker compose exec -T rails rspec
